apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-deployment
  labels:
    app: udagram
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram
  template:
    metadata:
      labels:
        app: udagram
    spec:
      containers:
        - name: udagram-api-user
          image: segbegnon/udagram-api-user
          ports:
            - containerPort: 80
        - name: udagram-api-feed
          image: segbegnon/udagram-api-feed
          ports:
            - containerPort: 80
        - name: reverseproxy
          image: segbegnon/reverseproxy
          ports:
            - containerPort: 80
        - name: udagram-frontend
          image: segbegnon/udagram-frontend
          ports:
            - containerPort: 80