name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Print Docker version
      run: docker --version
    
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    -
      name: Build and push "udagram-api-user"
      uses: docker/build-push-action@v2
      with:
        context: ./udagram_api_user/
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/udagram-api-user:latest
    
    -
      name: Build and push "udagram-api-feed"
      uses: docker/build-push-action@v2
      with:
        context: ./udagram_api_feed/
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/udagram-api-feed:latest   
    
    -
      name: Build and push "reverseproxy"
      uses: docker/build-push-action@v2
      with:
        context: ./udagram_reverseproxy/
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/reverseproxy:latest  
    
    -
      name: Build and push "udagram-frontend"
      uses: docker/build-push-action@v2
      with:
        context: ./udagram_frontend/
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/udagram-frontend:latest
